class Stack[T]:
    def __init__(self, max_size: int) -> None: ...
    
    def insert(self, value: T) -> None: ...
    def push(self, value: T) -> None: ...
    
    def delete(self) -> T: ...
    def pop(self) -> T: ...
